[network]
name = "devnet"
stacks_node_rpc_address = "http://localhost:20443"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "twice particular affair smile cart ritual music library best unit excuse bright tuition inquiry anchor aware ugly sing world open"
balance = 10_000_000_000_000
stx_address = "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM"

[accounts.wallet_1]
mnemonic = "sell invite acquire kitten bamboo drastic jelly vivid peace spawn twice guilt pave pen trash pretty park cube fragile unaware remain midnight betray rebuild"
balance = 10_000_000_000_000
stx_address = "ST1SJ3DTE5DN7X54YDH5D64R3BCB6A2AG2ZQ8YPD5"

[accounts.wallet_2]
mnemonic = "hold excess usual excess ring elephant install account glad dry fragile donkey gaze humble truck breeze nation gasp vacuum limb head keep delay hospital"
balance = 10_000_000_000_000
stx_address = "ST2CY5V39NHDPWSXMW9QDT3HC3GD6Q6XX4CFRK9AG"

[accounts.wallet_3]
mnemonic = "cycle puppy glare enroll cost improve round trend wrist mushroom scorpion tower claim oppose clever elephant dinosaur eight problem before frozen dune wagon high"
balance = 10_000_000_000_000
stx_address = "ST2JHG361ZXG51QTKY2NQCVBPPRRE2KZB1HR05NNC"

[accounts.wallet_4]
mnemonic = "board list obtain sugar hour worth raven scout denial thunder horse logic fury scorpion fold genuine phrase wealth news aim below celery when cabin"
balance = 10_000_000_000_000
stx_address = "ST2NEB84ASEZ1X5QBPF8WM6MH6YTJ0DTZZ9W89EAR"

[[devnet.plan.batches]]
id = 0
transactions = [
  { contract-publish = { contract-name = "stacks-capsule", expected-sender = "$deployer", path = "contracts/stacks-capsule.clar", clarity-version = 2, cost = 10000 }}
]

